import Head from 'next/head';
import styles from '@/styles/Home.module.scss';
import { gql, wpgraphql } from '../../lib/wpgrapghql';
import { use, useEffect, useState } from 'react';
import { NextPageContext } from 'next';

import Carousel from '@/components/Carousel/Carousel';
import Footer from '@/components/Footer/Footer';
import photo from '../../assets/slider-3.webp';
import president from '../../assets/higgins.png';
import fourthPageIcon from '../../assets/fourthPageIcon.png';
import sixthPageIcon from '../../assets/sixthPageIcon.png';
import Header from '@/components/Header/Header';
import flag1 from '../../assets/flags/flag-1.svg';
import flag2 from '../../assets/flags/flag-2.svg';
import flag3 from '../../assets/flags/flag-3.svg';
import flag4 from '../../assets/flags/flag-4.svg';
import flag5 from '../../assets/flags/flag-5.svg';
import flag6 from '../../assets/flags/flag-6.svg';
import flag7 from '../../assets/flags/flag-7.svg';
import flag8 from '../../assets/flags/flag-8.svg';
import flag9 from '../../assets/flags/flag-9.svg';
import flag10 from '../../assets/flags/flag-10.svg';
import flag11 from '../../assets/flags/flag-11.svg';
import Image from 'next/image';
import InfoBlock from '@/components/InfoBlock/InfoBlock';
import { GET_FLAGS_DATA } from '@/gql/queries';

export async function getServerSideProps({}: NextPageContext) {
  const sliderData: any = await wpgraphql.request(GET_FLAGS_DATA);

  return {
    props: {sliderData},
  }
}

const Fifth = ({sliderData: serverSliderData}: any) => {

  const contentPageFifth = serverSliderData.flags.nodes;
  

  const [currentFlag, setCurrentFlag] = useState(1);
  const [changeImage, setChangeImage] = useState(false);
  const [startX, setStartX] = useState(0);

  const chooseFlag = (e: any, id: any) => {
    setChangeImage(true);
    e.preventDefault();

    setCurrentFlag(id);
  }

  useEffect(() => {
    setTimeout(() => {
      setChangeImage(false);
    }, 500)
    
  }, [changeImage])
  
  return (
    <>
      <Head>
        <title>Thomas F Meagher</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="manifest" href="/manifest.json" />
      </Head>
      <main className="fifth-page" >
      <Header />

      <div className="fifth-page-flags" 
      >
        <div className="fifth-page-banner"
          // onTouchStart={handleTouchStart}
          // onTouchMove={handleTouchMove}
        >
          <div 
            className={`fifth-page-banner-left ${changeImage === false ? 'fade-in show' : 'fade-in'}`}
          >
            <Image
              src={contentPageFifth[currentFlag].featuredImage.node.mediaItemUrl}
              alt=""
              width={950}
              height={590}
            />
            
          </div>
          <div className="fifth-page-banner-rigth">
            <h2 className="fifth-page-banner-rigth-title">
              {contentPageFifth[currentFlag].title}
            </h2>
            <p className="fifth-page-banner-rigth-text">
              {contentPageFifth[currentFlag].excerpt.replace(/<\/?p>/g, '')}
            </p>
            
          </div>
        </div>
        <div className="fifth-page-flags-navigarion">
          {contentPageFifth.map((item: any, index: any) => 
            <div key={item.id} className="fifth-page-flags-img">
              <a href="" onClick={(e: any) => chooseFlag(e, (index + 1) - 1)}>
                <Image
                  src={item.featuredImage.node.mediaItemUrl}
                  alt=''
                  width={161}
                  height={100}
                />
              </a>
            </div>
          )}
        </div>
      </div>
      
      <Footer 
        prevLink={'/fourth'} prevImage={fourthPageIcon.src.toString()}
        nextLink={'/sixth'} nextImage={sixthPageIcon.src.toString()}
      />
      </main>
      <div className="fifth-page-wrapper-info-block">
        <InfoBlock text={'Select a flag below to find out more'} />
      </div>
    </>
  );
}

export default Fifth;
