import Head from 'next/head';
import Footer from '@/components/Footer/Footer';
import photo from '../../assets/slider-3.webp';
import president from '../../assets/higgins.png';
import eighthPageIcon from '../../assets/eighthPageIcon.png';
import secondPageIcon from '../../assets/secondPageIcon.png';
import Header from '@/components/Header/Header';


const contentPageSixth = [
  {id: 1, name: 'Micheal D Higgins', position: 'President', words: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra aliquam leo, vel vestibulum leo tempor eu. Mauris dolor erat, convallis et aliquet et, efficitur mollis eros. Cras fringilla, ligula convallis ultricies accumsan, dui lacus malesuada mauris.', photo: president},
  {id: 2, name: 'Katie Taylor2', position: 'gold medal winner at the olympic games', words: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra aliquam leo, vel vestibulum leo tempor eu. Mauris dolor erat, convallis et aliquet et, efficitur mollis eros. Cras fringilla, ligula convallis ultricies accumsan, dui lacus malesuada mauris.', photo: president},
  {id: 3, name: 'Katie Taylor3', position: 'gold medal winner at the olympic games', words: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra aliquam leo, vel vestibulum leo tempor eu. Mauris dolor erat, convallis et aliquet et, efficitur mollis eros. Cras fringilla, ligula convallis ultricies accumsan, dui lacus malesuada mauris.', photo: photo},
  {id: 4, name: 'Katie Taylor4', position: 'gold medal winner at the olympic games', words: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra aliquam leo, vel vestibulum leo tempor eu. Mauris dolor erat, convallis et aliquet et, efficitur mollis eros. Cras fringilla, ligula convallis ultricies accumsan, dui lacus malesuada mauris.', photo: photo},
  {id: 5, name: 'Katie Taylor5', position: 'gold medal winner at the olympic games', words: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra aliquam leo, vel vestibulum leo tempor eu. Mauris dolor erat, convallis et aliquet et, efficitur mollis eros. Cras fringilla, ligula convallis ultricies accumsan, dui lacus malesuada mauris.', photo: photo},
  {id: 6, name: 'Katie Taylor6', position: 'gold medal winner at the olympic games', words: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra aliquam leo, vel vestibulum leo tempor eu. Mauris dolor erat, convallis et aliquet et, efficitur mollis eros. Cras fringilla, ligula convallis ultricies accumsan, dui lacus malesuada mauris.', photo: photo},
  {id: 7, name: 'Katie Taylor7', position: 'gold medal winner at the olympic games', words: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra aliquam leo, vel vestibulum leo tempor eu. Mauris dolor erat, convallis et aliquet et, efficitur mollis eros. Cras fringilla, ligula convallis ultricies accumsan, dui lacus malesuada mauris.', photo: photo},
  {id: 8, name: 'Katie Taylor8', position: 'gold medal winner at the olympic games', words: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra aliquam leo, vel vestibulum leo tempor eu. Mauris dolor erat, convallis et aliquet et, efficitur mollis eros. Cras fringilla, ligula convallis ultricies accumsan, dui lacus malesuada mauris.', photo: photo},
  {id: 9, name: 'Katie Taylor9', position: 'gold medal winner at the olympic games', words: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra aliquam leo, vel vestibulum leo tempor eu. Mauris dolor erat, convallis et aliquet et, efficitur mollis eros. Cras fringilla, ligula convallis ultricies accumsan, dui lacus malesuada mauris.', photo: photo},
];

const firstColumn = [
  {keyValue: 'q'},
  {keyValue: 'w'},
  {keyValue: 'e'},
  {keyValue: 'r'},
  {keyValue: 't'},
  {keyValue: 'y'},
  {keyValue: 'u'},
  {keyValue: 'i'},
  {keyValue: 'o'},
  {keyValue: 'p'},
  {keyValue: 'backspace'},
];
// ~!$%^&*_=+}{'?-.

const secondColumn = [
  {keyValue: 'a'},
  {keyValue: 's'},
  {keyValue: 'd'},
  {keyValue: 'f'},
  {keyValue: 'g'},
  {keyValue: 'h'},
  {keyValue: 'j'},
  {keyValue: 'k'},
  {keyValue: 'l'},
  {keyValue: ';'},
  {keyValue: 'enter'},
];

const thirdColumn = [
  {keyValue: 'row up'},
  {keyValue: 'z'},
  {keyValue: 'x'},
  {keyValue: 'c'},
  {keyValue: 'v'},
  {keyValue: 'b'},
  {keyValue: 'n'},
  {keyValue: 'm'},
  {keyValue: ','},
  {keyValue: '.'},
  {keyValue: '?'},
  {keyValue: 'row up'},
];

const fourthColumn = [
  {keyValue: '&123'},
  {keyValue: 'Ctrl'},
  {keyValue: '@'},
  {keyValue: 'space'},
  {keyValue: '<'},
  {keyValue: '>'},
  {keyValue: 'keyboard'},
];

const Tenth = () => {

  return (
    <>
      <Head>
        <title>Thomas F Meagher</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="manifest" href="/manifest.json" />
      </Head>

      <main className="tenth-page" >
        <Header />

        <div className="tenth-page-main">
          <h2 className="tenth-page-main-title">
            Enter your email address to receive the Protocol for the national flag
          </h2>
          <div className="tenth-page-main-input">
            <p>your email address</p>
            <a href="">submit</a>
          </div>
          <div className="tenth-page-main-keyboard">
            <div className="tenth-page-main-keyboard-keys tenth-page-main-keyboard-keys-first">
              {firstColumn.map(keyOne => 
                <a key={keyOne.keyValue}>{keyOne.keyValue}</a>  
              )}
            </div>

            <div className="tenth-page-main-keyboard-keys tenth-page-main-keyboard-keys-second">
              {secondColumn.map(keyOne => 
                <a key={keyOne.keyValue}>{keyOne.keyValue}</a>  
              )}
            </div>

            <div className="tenth-page-main-keyboard-keys tenth-page-main-keyboard-keys-third">
              {thirdColumn.map(keyOne => 
                <a key={keyOne.keyValue}>{keyOne.keyValue}</a>  
              )}
            </div>

            <div className="tenth-page-main-keyboard-keys tenth-page-main-keyboard-keys-fourth">
              {fourthColumn.map(keyOne => 
                <a key={keyOne.keyValue}>{keyOne.keyValue}</a>  
              )}
            </div>
          </div>
        </div>
        
        <Footer 
          prevLink={'/ninth'} prevImage={eighthPageIcon.src.toString()}
          nextLink={'/second'} nextImage={secondPageIcon.src.toString()}
        />
      </main>
    </>
  );
}

export default Tenth;
