// @ts-ignore
import Head from 'next/head';
import photo from '../../assets/slider-3.webp';
import president from '../../assets/higgins.png';
import HTMLFlipBook from 'react-pageflip';
import Image from 'next/image';
import React, { useRef } from 'react';
import { NextPageContext } from 'next';
import { wpgraphql } from '@/lib/wpgrapghql';
import { GET_POSTS } from '@/gql/queries';

export async function getServerSideProps({}: NextPageContext) {
  const posts: any = await wpgraphql.request(GET_POSTS);

  return {
    props: {posts},
  }
}


// eslint-disable-next-line react/display-name
const PageCover = React.forwardRef((props: any, ref: any) => {
  return (
    <div className="page page-cover" ref={ref} data-density="--soft">
      <div className="page-content">
        <h2>{props.children}</h2>
      </div>
    </div>
  );
});

// eslint-disable-next-line react/display-name
const Page = React.forwardRef((props: any, ref: any) => {
  return (
    <>
      <div className="page" ref={ref}>
        <div className="page-content">
          <h2 className="page-header">Page header - {props.number}</h2>
          <div className="page-image"></div>
          <div className="page-text">{props.children}</div>
          <div className="page-footer">{props.number + 1}</div>
        </div>
      </div>
    </>
  );
});

const Ninth = ({currentMagazine, setCurrentMagazine}: any) => {

  const combinedRegex = /data="([^"]+)"|src="([^"]+)"/g;

  // Extract the links using the combined regex
  const linkMatches = currentMagazine.content.match(combinedRegex);
  const links = linkMatches ? linkMatches.map((match: string) => match.split(/data=|src=/)[1].slice(1, -1)) : [];
  const bookRef = useRef(null);
  
  return (
    <>
      <Head>
        <title>Thomas F Meagher</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="manifest" href="/manifest.json" />
      </Head>

      <div className="ninth-page-main" >
        {/* @ts-ignore */}
        <HTMLFlipBook
          width={550}
          height={733}
          size="stretch"
          minWidth={315}
          maxWidth={1000}
          minHeight={400}
          maxHeight={1533}
          maxShadowOpacity={0.5}
          showCover={false}
          mobileScrollSupport={true}
          className="magazine"
        >
          {links.map((link: string, index: number) => (
              <Page number={index} key={link}>
                <Image
                  src={link}
                  // width={300}
                  // height={500}
                  fill
                  alt=''
                />
              </Page>
          ))}
        </HTMLFlipBook>
        <a href="" className="close-btn"
          onClick={(e) => {
            e.preventDefault();
            setCurrentMagazine();
          }}
        >close X</a>
      </div>
    </>
  );
}

export default Ninth;
