import Head from 'next/head';
import styles from '@/styles/Home.module.scss';
import { gql, wpgraphql } from '../../lib/wpgrapghql';
import { useEffect, useState } from 'react';
import { NextPageContext } from 'next';
import Image from 'next/image';
import sign from '../../assets/sign.svg';
import Carousel from '@/components/Carousel/Carousel';

import { Swiper, SwiperSlide } from 'swiper/react';

// Import Swiper styles
import 'swiper/css';
import { GET_SECOND_PAGE_DATA } from '@/gql/queries';

export async function getServerSideProps({}: NextPageContext) {
  const sliderData: any = await wpgraphql.request(GET_SECOND_PAGE_DATA);

  return {
    props: {sliderData},
  }
}


export default function Second ({ sliderData: serverSliderData }: any) {
  useEffect(() =>{
    document.body.style.background = 'white';
  })

  return (
    <>
      <Head>
        <title>Thomas F Meagher</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="manifest" href="/manifest.json" />
      </Head>
      <main className={`${styles.main} second-page fade-enter`} >
        <Carousel 
          sliderData={serverSliderData.page.secondPageSliders}
        />  
      </main>
    </>
  );
}
