import Head from 'next/head';
import styles from '@/styles/Home.module.scss';
import { gql, wpgraphql } from '../../lib/wpgrapghql';
import { useState } from 'react';
import { NextPageContext } from 'next';
import Image from 'next/image';
import sign from '../../assets/sign.svg';
import Carousel from '@/components/Carousel/Carousel';

import { Swiper, SwiperSlide } from 'swiper/react';

// Import Swiper styles
import 'swiper/css';

const GetAllPosts = gql`
  query getPosts {
    posts {
      nodes {
        id
        slug
        title
        uri
      }
    }
  }
`;

// const data = wpgraphql.request(GetAllPosts);

// const getAllPosts = async () => {
//   const { posts } = await wpgraphql.request(GetAllPosts);
//   console.log(posts);
//   return posts;
// };

// getAllPosts();

type One = {
  posts: Nodes
}

type Nodes = {
  nodes: Posts
}

type Posts = {
  map(arg0: (post: { title: string; id: string; }) => JSX.Element): import("react").ReactNode;
  length: number;
  id: string
  slug: string
  title: string
  uri: string
}

interface PostsPageProps {
  posts:One;
}

export default function Home({ posts: serverPosts }: PostsPageProps) {
  const [postsList, setPostsList] = useState(serverPosts.posts.nodes);

  console.log('serverPosts.id', serverPosts);

  return (
    <>
      <Head>
        <title>Thomas F Meagher</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="manifest" href="/manifest.json" />
      </Head>
      <main className={`${styles.main} second-page`} >
        <Carousel />  
        {/* <Swiper
      spaceBetween={50}
      slidesPerView={3}
      onSlideChange={() => console.log('slide change')}
      onSwiper={(swiper) => console.log(swiper)}
    >
      <SwiperSlide>Slide 1</SwiperSlide>
      <SwiperSlide>Slide 2</SwiperSlide>
      <SwiperSlide>Slide 3</SwiperSlide>
      <SwiperSlide>Slide 4</SwiperSlide>
      ...
    </Swiper> */}
      </main>
    </>
  );
}

export async function getServerSideProps({}: NextPageContext) {
  const posts: any = await wpgraphql.request(GetAllPosts);

  return {
    props: {posts},
  }
}
