import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import { gql, wpgraphql } from '../lib/wpgrapghql';
import { JSXElementConstructor, Key, ReactElement, ReactFragment, useEffect, useState } from 'react';
import { NextPageContext } from 'next';

const GetAllPosts = gql`
  query getPosts {
    posts {
      nodes {
        title
      }
    }
  }
`;

// const data = wpgraphql.request(GetAllPosts);

// const getAllPosts = async () => {
//   const { posts } = await wpgraphql.request(GetAllPosts);
//   console.log(posts);
//   return posts;
// };

// getAllPosts();

interface PostsPageProps {
  posts:any;
}

export default function Home({ posts: serverPosts }: PostsPageProps) {
  const [postList, setPostList] = useState(serverPosts.posts.nodes);

  console.log(serverPosts);

  return (
    <>
      <Head>
        <title>Thomas F Meagher</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {postList.length === 0 ? (
          <p>loading</p>
        ) : (
          postList.map((item: { title: string }) => (
            <div className="product-item" key={Number(item.title)}>
              <div>{item.title}</div>
            </div>
          ))
        )}
        <h1 className={styles.title}>Thomas F Meagher</h1>
        <pre></pre>
      </main>
    </>
  );
}

export async function getServerSideProps({req, res}: NextPageContext) {
  const posts: any = await wpgraphql.request(GetAllPosts);

  return {
    props: {posts},
  }
}
